apiVersion: apps/v1
kind: Deployment
metadata:
  name: icapp
  namespace: default
  labels:
    app: icapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icapp
  template:
    metadata:
      labels:
        app: icapp
    spec:
      containers:
      - image: ghcr.io/mohammad-ammar14/incident-mgmt:0.0.0
        name: icapp
        ports:
        - containerPort: 9898
          name: http
